### ISSUE TITLE
I want to add more Algorithms on Sorting Techniques

### ISSUE THREAD

**Issue by knockcat** [ravya1108/hactoberfest2022#205]
Please assign me this taks, I am going to add quality code and covers all the algorithms.

**Comment by knockcat** [comment]
![image](https://github.com/ravya1108/hactoberfest2023/assets/85362504/222359ab-5cc7-49cc-ab2a-2e274e847d70)

**Comment by knockcat** [comment]
I want to add all these techiniques
This pull request covers the heap sort both max and min.

// Heap Sort (Max) Ascending Order Sorting

/* 
Time Complexity
     Overall :	O(nlogn)
     for creating and building heap: O(n)
*/


// Heap Sort (Min) Descending Order Sorting

/* 
Time Complexity
     Overall :	O(nlogn)
     for creating and building heap: O(n)
*/

**Comment by kashyapanjali** [comment]
assign to me in this particular hactoberfest

**Comment by Ashima2003** [comment]
I wish to contribute. Kindly assign this to me.

**Comment by saku1331** [comment]
hello ! Please assign me this. I want to contribute.

**Comment by Vaibhav112003** [comment]
Hello  Ma'am , Please assign me this , I want to contribute for this

**Comment by kashyapanjali** [comment]
please remove me to this repo
